# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4780585e8d729f443ef0ac67eb58830fec3a5eaa7ec7b65cd0c7bd04cdce171cd76613394bc26bf807605c179ee978778f1deaa762f632a0791c01844fbdba5a

test:
  secret_key_base: c1953b54674e8b7bdfe9bcd2adb3e1061bd495e6198bc91bf1c566a0a04ef85d16da99dabb8818d05d21fd06c65bce06e2e674661a07dfe55d87ee6e57c2f2d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
